import { Player } from './types';

export const PLAYERS_DB: Player[] = [
  // ATTACKERS
  {
    id: 'p1',
    name: 'Lionel Messi',
    rating: 98,
    position: 'ST',
    category: 'ST',
    nation: 'Argentina',
    nationFlag: '🇦🇷',
    club: 'Inter Miami',
    clubLogo: '🦩',
    league: 'MLS',
    era: 'Current',
    playstyle: 'Technical Dribbler',
    cardType: 'TOTY',
    auraRating: 99,
    avatarSeed: 'messi',
    stats: { pac: 91, sho: 96, pas: 98, dri: 99, def: 40, phy: 72 },
    achievements: ['8x Ballon d\'Or', 'World Cup Winner', 'Copa America Winner']
  },
  {
    id: 'p2',
    name: 'Cristiano Ronaldo',
    rating: 97,
    position: 'ST',
    category: 'ST',
    nation: 'Portugal',
    nationFlag: '🇵🇹',
    club: 'Al Nassr',
    clubLogo: '🟡',
    league: 'Saudi Pro League',
    era: 'Current',
    playstyle: 'Power Finisher',
    cardType: 'Legend',
    auraRating: 99,
    avatarSeed: 'ronaldo',
    stats: { pac: 93, sho: 98, pas: 82, dri: 88, def: 35, phy: 90 },
    achievements: ['5x Ballon d\'Or', '5x Champions League', 'Euro Champion']
  },
  {
    id: 'p3',
    name: 'Kylian Mbappé',
    rating: 95,
    position: 'ST',
    category: 'ST',
    nation: 'France',
    nationFlag: '🇫🇷',
    club: 'Real Madrid',
    clubLogo: '👑',
    league: 'LaLiga',
    era: 'Current',
    playstyle: 'Speed Ster',
    cardType: 'TOTY',
    auraRating: 96,
    avatarSeed: 'mbappe',
    stats: { pac: 99, sho: 94, pas: 84, dri: 93, def: 36, phy: 80 },
    achievements: ['World Cup Winner', 'Ligue 1 Golden Boot']
  },
  {
    id: 'p4',
    name: 'Erling Haaland',
    rating: 94,
    position: 'ST',
    category: 'ST',
    nation: 'Norway',
    nationFlag: '🇳🇴',
    club: 'Manchester City',
    clubLogo: '🔵',
    league: 'Premier League',
    era: 'Current',
    playstyle: 'Target Man',
    cardType: 'Gold',
    auraRating: 94,
    avatarSeed: 'haaland',
    stats: { pac: 89, sho: 95, pas: 68, dri: 81, def: 45, phy: 91 },
    achievements: ['Treble Winner', 'Premier League Goal Record']
  },
  {
    id: 'p5',
    name: 'Pelé',
    rating: 99,
    position: 'ST',
    category: 'ST',
    nation: 'Brazil',
    nationFlag: '🇧🇷',
    club: 'Santos',
    clubLogo: '⚪',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Samba Maestro',
    cardType: 'Legend',
    auraRating: 100,
    avatarSeed: 'pele',
    stats: { pac: 96, sho: 97, pas: 93, dri: 98, def: 55, phy: 84 },
    achievements: ['3x World Cup Winner', 'Athlete of the Century']
  },
  {
    id: 'p6',
    name: 'Diego Maradona',
    rating: 98,
    position: 'CAM',
    category: 'MID',
    nation: 'Argentina',
    nationFlag: '🇦🇷',
    club: 'Napoli',
    clubLogo: '🔵',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Hand of God Dribbler',
    cardType: 'Legend',
    auraRating: 99,
    avatarSeed: 'maradona',
    stats: { pac: 92, sho: 93, pas: 97, dri: 99, def: 42, phy: 78 },
    achievements: ['World Cup Winner 1986', 'Golden Ball Winner']
  },
  {
    id: 'p7',
    name: 'Ronaldinho',
    rating: 95,
    position: 'LW',
    category: 'ST',
    nation: 'Brazil',
    nationFlag: '🇧🇷',
    club: 'Barcelona',
    clubLogo: '🔵🔴',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Trickster Supreme',
    cardType: 'Icon',
    auraRating: 98,
    avatarSeed: 'ronaldinho',
    stats: { pac: 94, sho: 89, pas: 91, dri: 97, def: 38, phy: 81 },
    achievements: ['Ballon d\'Or 2005', 'World Cup & UCL Winner']
  },
  {
    id: 'p8',
    name: 'Thierry Henry',
    rating: 93,
    position: 'LW',
    category: 'ST',
    nation: 'France',
    nationFlag: '🇫🇷',
    club: 'Arsenal',
    clubLogo: '🔴',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Finesse King',
    cardType: 'Icon',
    auraRating: 94,
    avatarSeed: 'henry',
    stats: { pac: 96, sho: 91, pas: 84, dri: 90, def: 41, phy: 82 },
    achievements: ['Invincible Premier League', 'All-Time Arsenal Top Scorer']
  },
  {
    id: 'p9',
    name: 'Vinicius Jr',
    rating: 91,
    position: 'LW',
    category: 'ST',
    nation: 'Brazil',
    nationFlag: '🇧🇷',
    club: 'Real Madrid',
    clubLogo: '👑',
    league: 'LaLiga',
    era: 'Current',
    playstyle: 'Samba Speedster',
    cardType: 'Gold',
    auraRating: 92,
    avatarSeed: 'vinicius',
    stats: { pac: 97, sho: 84, pas: 82, dri: 92, def: 32, phy: 71 },
    achievements: ['2x Champions League Winner', 'UCL Young Player']
  },
  {
    id: 'p10',
    name: 'Mohamed Salah',
    rating: 90,
    position: 'RW',
    category: 'ST',
    nation: 'Egypt',
    nationFlag: '🇪🇬',
    club: 'Liverpool',
    clubLogo: '🔴',
    league: 'Premier League',
    era: 'Current',
    playstyle: 'Inside Forward',
    cardType: 'Gold',
    auraRating: 91,
    avatarSeed: 'salah',
    stats: { pac: 90, sho: 89, pas: 83, dri: 89, def: 45, phy: 76 },
    achievements: ['Premier League Golden Boot', 'Champions League Winner']
  },
  {
    id: 'p11',
    name: 'Zlatan Ibrahimović',
    rating: 92,
    position: 'ST',
    category: 'ST',
    nation: 'Sweden',
    nationFlag: '🇸🇪',
    club: 'AC Milan',
    clubLogo: '🔴⚫',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Acrobatic Finisher',
    cardType: 'Legend',
    auraRating: 99.9, // Meme Aura!
    avatarSeed: 'zlatan',
    stats: { pac: 83, sho: 93, pas: 84, dri: 88, def: 34, phy: 92 },
    achievements: ['Zlatan does not need achievements, achievements need Zlatan.']
  },
  {
    id: 'p12',
    name: 'Harry Kane',
    rating: 90,
    position: 'ST',
    category: 'ST',
    nation: 'England',
    nationFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    club: 'Bayern Munich',
    clubLogo: '🔴⚪',
    league: 'Bundesliga',
    era: 'Current',
    playstyle: 'Deep Poacher',
    cardType: 'Gold',
    auraRating: 88,
    avatarSeed: 'kane',
    stats: { pac: 72, sho: 93, pas: 85, dri: 83, def: 48, phy: 84 },
    achievements: ['European Golden Shoe', 'England All-Time Scorer']
  },
  {
    id: 'p13',
    name: 'Johan Cruyff',
    rating: 96,
    position: 'CF',
    category: 'ST',
    nation: 'Netherlands',
    nationFlag: '🇳🇱',
    club: 'Ajax',
    clubLogo: '⚪🔴',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Total Footballer',
    cardType: 'Legend',
    auraRating: 98,
    avatarSeed: 'cruyff',
    stats: { pac: 91, sho: 92, pas: 94, dri: 96, def: 42, phy: 73 },
    achievements: ['3x Ballon d\'Or', 'Inventor of Total Football']
  },

  // MIDFIELDERS
  {
    id: 'p14',
    name: 'Kevin De Bruyne',
    rating: 92,
    position: 'CM',
    category: 'MID',
    nation: 'Belgium',
    nationFlag: '🇧🇪',
    club: 'Manchester City',
    clubLogo: '🔵',
    league: 'Premier League',
    era: 'Current',
    playstyle: 'Laser Passer',
    cardType: 'Gold',
    auraRating: 93,
    avatarSeed: 'debruyne',
    stats: { pac: 74, sho: 86, pas: 95, dri: 87, def: 65, phy: 78 },
    achievements: ['Multiple Premier League Champion', 'UCL Playmaker of the Year']
  },
  {
    id: 'p15',
    name: 'Zinedine Zidane',
    rating: 96,
    position: 'CAM',
    category: 'MID',
    nation: 'France',
    nationFlag: '🇫🇷',
    club: 'Real Madrid',
    clubLogo: '👑',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Elegant Maestro',
    cardType: 'Legend',
    auraRating: 98,
    avatarSeed: 'zidane',
    stats: { pac: 83, sho: 90, pas: 96, dri: 95, def: 68, phy: 86 },
    achievements: ['Ballon d\'Or 1998', 'World Cup Winner', 'UCL Volley Goal']
  },
  {
    id: 'p16',
    name: 'Jude Bellingham',
    rating: 91,
    position: 'CAM',
    category: 'MID',
    nation: 'England',
    nationFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    club: 'Real Madrid',
    clubLogo: '👑',
    league: 'LaLiga',
    era: 'Current',
    playstyle: 'Box-to-Box Warrior',
    cardType: 'Future Star',
    auraRating: 95,
    avatarSeed: 'bellingham',
    stats: { pac: 83, sho: 85, pas: 86, dri: 88, def: 78, phy: 84 },
    achievements: ['LaLiga POTY', 'UCL Champion 2024']
  },
  {
    id: 'p17',
    name: 'David Beckham',
    rating: 89,
    position: 'RM',
    category: 'MID',
    nation: 'England',
    nationFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    club: 'Manchester United',
    clubLogo: '🔴',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Golden Crosser',
    cardType: 'Icon',
    auraRating: 95,
    avatarSeed: 'beckham',
    stats: { pac: 79, sho: 84, pas: 95, dri: 82, def: 60, phy: 76 },
    achievements: ['Treble Winner 1999', 'Free Kick Specialist']
  },
  {
    id: 'p18',
    name: 'Andrea Pirlo',
    rating: 92,
    position: 'CM',
    category: 'MID',
    nation: 'Italy',
    nationFlag: '🇮🇹',
    club: 'Juventus',
    clubLogo: '⚪⚫',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Deep Architect',
    cardType: 'Icon',
    auraRating: 94,
    avatarSeed: 'pirlo',
    stats: { pac: 68, sho: 79, pas: 96, dri: 91, def: 62, phy: 66 },
    achievements: ['World Cup Winner 2006', 'Champions League Masterclass']
  },
  {
    id: 'p19',
    name: 'Rodri',
    rating: 92,
    position: 'CDM',
    category: 'MID',
    nation: 'Spain',
    nationFlag: '🇪🇸',
    club: 'Manchester City',
    clubLogo: '🔵',
    league: 'Premier League',
    era: 'Current',
    playstyle: 'Defensive Anchor',
    cardType: 'TOTY',
    auraRating: 94,
    avatarSeed: 'rodri',
    stats: { pac: 66, sho: 80, pas: 88, dri: 84, def: 90, phy: 89 },
    achievements: ['Ballon d\'Or 2024', 'UCL Match Winner Goal']
  },
  {
    id: 'p20',
    name: 'Luka Modrić',
    rating: 89,
    position: 'CM',
    category: 'MID',
    nation: 'Croatia',
    nationFlag: '🇭🇷',
    club: 'Real Madrid',
    clubLogo: '👑',
    league: 'LaLiga',
    era: 'Current',
    playstyle: 'Trivela Master',
    cardType: 'Gold',
    auraRating: 93,
    avatarSeed: 'modric',
    stats: { pac: 72, sho: 76, pas: 89, dri: 88, def: 72, phy: 66 },
    achievements: ['Ballon d\'Or 2018', '6x UEFA Champions League']
  },
  {
    id: 'p21',
    name: 'Jamal Musiala',
    rating: 88,
    position: 'CAM',
    category: 'MID',
    nation: 'Germany',
    nationFlag: '🇩🇪',
    club: 'Bayern Munich',
    clubLogo: '🔴⚪',
    league: 'Bundesliga',
    era: 'Current',
    playstyle: 'Snake-like Dribbler',
    cardType: 'Future Star',
    auraRating: 90,
    avatarSeed: 'musiala',
    stats: { pac: 85, sho: 80, pas: 84, dri: 92, def: 42, phy: 64 },
    achievements: ['Bundesliga Title Goal', 'Golden Boy Nominee']
  },

  // DEFENDERS
  {
    id: 'p22',
    name: 'Paolo Maldini',
    rating: 97,
    position: 'CB',
    category: 'DEF',
    nation: 'Italy',
    nationFlag: '🇮🇹',
    club: 'AC Milan',
    clubLogo: '🔴⚫',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Art of Defense',
    cardType: 'Legend',
    auraRating: 98,
    avatarSeed: 'maldini',
    stats: { pac: 86, sho: 56, pas: 75, dri: 80, def: 98, phy: 85 },
    achievements: ['5x Champions League Winner', 'Milan Legend']
  },
  {
    id: 'p23',
    name: 'Virgil van Dijk',
    rating: 91,
    position: 'CB',
    category: 'DEF',
    nation: 'Netherlands',
    nationFlag: '🇳🇱',
    club: 'Liverpool',
    clubLogo: '🔴',
    league: 'Premier League',
    era: 'Current',
    playstyle: 'Commanding Wall',
    cardType: 'Gold',
    auraRating: 94,
    avatarSeed: 'vandijk',
    stats: { pac: 78, sho: 60, pas: 72, dri: 72, def: 91, phy: 89 },
    achievements: ['Champions League Winner', 'UEFA Player of the Year']
  },
  {
    id: 'p24',
    name: 'Roberto Carlos',
    rating: 92,
    position: 'LB',
    category: 'DEF',
    nation: 'Brazil',
    nationFlag: '🇧🇷',
    club: 'Real Madrid',
    clubLogo: '👑',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Bullet Free-kicker',
    cardType: 'Icon',
    auraRating: 95,
    avatarSeed: 'carlos',
    stats: { pac: 94, sho: 85, pas: 82, dri: 84, def: 81, phy: 87 },
    achievements: ['World Cup Winner 2002', 'Physic-defying Free Kick vs France']
  },
  {
    id: 'p25',
    name: 'Philipp Lahm',
    rating: 91,
    position: 'RB',
    category: 'DEF',
    nation: 'Germany',
    nationFlag: '🇩🇪',
    club: 'Bayern Munich',
    clubLogo: '🔴',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Tactical Genius',
    cardType: 'Icon',
    auraRating: 91,
    avatarSeed: 'lahm',
    stats: { pac: 80, sho: 68, pas: 86, dri: 83, def: 91, phy: 74 },
    achievements: ['World Cup Winning Captain', '8x Bundesliga Cup Champion']
  },
  {
    id: 'p26',
    name: 'Antonio Rüdiger',
    rating: 88,
    position: 'CB',
    category: 'DEF',
    nation: 'Germany',
    nationFlag: '🇩🇪',
    club: 'Real Madrid',
    clubLogo: '👑',
    league: 'LaLiga',
    era: 'Current',
    playstyle: 'Aggressive Destroyer',
    cardType: 'Gold',
    auraRating: 92,
    avatarSeed: 'rudiger',
    stats: { pac: 82, sho: 54, pas: 70, dri: 71, def: 87, phy: 86 },
    achievements: ['Champions League Winner with Chelsea & RM']
  },
  {
    id: 'p27',
    name: 'Alphonso Davies',
    rating: 86,
    position: 'LB',
    category: 'DEF',
    nation: 'Canada',
    nationFlag: '🇨🇦',
    club: 'Bayern Munich',
    clubLogo: '🔴⚪',
    league: 'Bundesliga',
    era: 'Current',
    playstyle: 'Roadrunner Back',
    cardType: 'Future Star',
    auraRating: 89,
    avatarSeed: 'davies',
    stats: { pac: 96, sho: 68, pas: 78, dri: 84, def: 77, phy: 78 },
    achievements: ['Champions League Treble Winner']
  },
  {
    id: 'p28',
    name: 'Achraf Hakimi',
    rating: 86,
    position: 'RB',
    category: 'DEF',
    nation: 'Morocco',
    nationFlag: '🇲🇦',
    club: 'Paris Saint-Germain',
    clubLogo: '🗼',
    league: 'Ligue 1',
    era: 'Current',
    playstyle: 'Attack Engine',
    cardType: 'Gold',
    auraRating: 88,
    avatarSeed: 'hakimi',
    stats: { pac: 93, sho: 75, pas: 80, dri: 82, def: 76, phy: 78 },
    achievements: ['World Cup 4th Place Historic Run', 'Ligue 1 Champion']
  },
  {
    id: 'p29',
    name: 'Cafu',
    rating: 93,
    position: 'RB',
    category: 'DEF',
    nation: 'Brazil',
    nationFlag: '🇧🇷',
    club: 'AC Milan',
    clubLogo: '🔴⚫',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Endless Engine',
    cardType: 'Icon',
    auraRating: 94,
    avatarSeed: 'cafu',
    stats: { pac: 92, sho: 62, pas: 81, dri: 84, def: 90, phy: 88 },
    achievements: ['2x World Cup Winning Captain', 'UCL Legend']
  },

  // GOALKEEPERS
  {
    id: 'p30',
    name: 'Lev Yashin',
    rating: 96,
    position: 'GK',
    category: 'GK',
    nation: 'Russia',
    nationFlag: '🇷🇺',
    club: 'Dynamo Moscow',
    clubLogo: '🔵',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Black Spider Saves',
    cardType: 'Legend',
    auraRating: 98,
    avatarSeed: 'yashin',
    stats: { pac: 60, sho: 20, pas: 71, dri: 53, def: 96, phy: 88 }, // mapped custom
    achievements: ['Only Goalkeeper to win Ballon d\'Or']
  },
  {
    id: 'p31',
    name: 'Alisson Becker',
    rating: 89,
    position: 'GK',
    category: 'GK',
    nation: 'Brazil',
    nationFlag: '🇧🇷',
    club: 'Liverpool',
    clubLogo: '🔴',
    league: 'Premier League',
    era: 'Current',
    playstyle: '1v1 Sweeper',
    cardType: 'Gold',
    auraRating: 90,
    avatarSeed: 'alisson',
    stats: { pac: 55, sho: 15, pas: 85, dri: 54, def: 90, phy: 83 },
    achievements: ['Champions League Winner', 'Copa America Winner']
  },
  {
    id: 'p32',
    name: 'Gianluigi Buffon',
    rating: 94,
    position: 'GK',
    category: 'GK',
    nation: 'Italy',
    nationFlag: '🇮🇹',
    club: 'Juventus',
    clubLogo: '⚪⚫',
    league: 'Icons',
    era: 'Legend',
    playstyle: 'Goliath Guard',
    cardType: 'Icon',
    auraRating: 96,
    avatarSeed: 'buffon',
    stats: { pac: 50, sho: 10, pas: 74, dri: 48, def: 94, phy: 82 },
    achievements: ['World Cup Winner 2006', 'Serie A Clean Sheets Record']
  },

  // FUN AURA CARDS
  {
    id: 'p33',
    name: 'Antony',
    rating: 82,
    position: 'RW',
    category: 'ST',
    nation: 'Brazil',
    nationFlag: '🇧🇷',
    club: 'Manchester United',
    clubLogo: '🔴',
    league: 'Premier League',
    era: 'Current',
    playstyle: '360° Spin Artist',
    cardType: 'Future Star',
    auraRating: 101, // Legendary Aura Limit breaker
    avatarSeed: 'antony',
    stats: { pac: 80, sho: 70, pas: 72, dri: 84, def: 35, phy: 68 },
    achievements: ['Completed 3 consecutive spins on live television', 'Influenced all soccer physics']
  },
  {
    id: 'p34',
    name: 'Harry Maguire',
    rating: 84,
    position: 'CB',
    category: 'DEF',
    nation: 'England',
    nationFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    club: 'Manchester United',
    clubLogo: '🔴',
    league: 'Premier League',
    era: 'Current',
    playstyle: 'Slabhead Shield',
    cardType: 'Gold',
    auraRating: 92,
    avatarSeed: 'maguire',
    stats: { pac: 52, sho: 60, pas: 68, dri: 66, def: 84, phy: 88 },
    achievements: ['Carried the entire English media industry', 'Aggressive header expert']
  }
];
